### ISSUE TITLE
fecha.parse method is allowing an invalid and a malformed dates

### ISSUE THREAD

**Issue by madrabaz** [taylorhakes/fecha#22] opened 2016-11-11 12:40 UTC
I'd expected to get a ```false``` return or an exception when I called the ```fecha.parse``` method  with  an invalid and a malformed dates. But it parsed them successfully.  Is this the desired result?

Invalid: Date parts are not in the valid ranges (12 >= Month >= 1, 31>= Day>= 1, 23>=Hour>= 0 ...)
```javascript
fecha.parse('2016-44-99', 'YYYY-MM-DD'); // Sat Nov 12 2016 21:39:00 GMT+0300
fecha.parse('2016-11-11 44:44', 'YYYY-MM-DD HH:mm'); // Sat Nov 12 2016 20:44:00 GMT+0300
```
Malformed: Supplied date string does not match the format
```javascript
fecha.parse('2016-1-1', 'YYYY-MM-DD'); // Fri Jan 01 2016 01:00:00 GMT+0400
fecha.parse('2016-11-11 3:4', 'YYYY-MM-DD HH:mm'); // Fri Nov 11 2016 03:04:00 GMT+0300
```
Invalid & Malformed:
```javascript
fecha.parse('2016-9876-123', 'YYYY-MM-DD'); // Tue Apr 16 2024 00:00:00 GMT+0300
fecha.parse('2016-11-11 4433:3344', 'YYYY-MM-DD HH:mm'); // Sat Nov 12 2016 20:33:00 GMT+0300
```
Tested on: Google Chrome Version 54.0.2840.71 m (Windows 10)

Thanks,

**Comment by madrabaz** [comment] 2016-12-01 17:53
Hi @taylorhakes, do you have any comment about this?

**Comment by taylorhakes** [comment] 2016-12-03 22:38
Yes, this is the intended behavior. moment.js behaves very similar (without the strict parameter). The library is meant to help with parsing valid date strings. It wasn't meant to parse invalid date strings. I will add something about this in the readme because it's not stated anywhere.

I would not be opposed to adding a strict version of the parser, if it doesn't add much bloat.

**Comment by k15a** [comment] 2018-06-08 14:27
Maybe the strict version could parse the date and format it again and then check if both strings are the same?

**Comment by blujedis** [comment] 2019-07-13 01:01
This is stale but, thought I'd bump. This lib claims to parse/format dates. Not parse/format NOT dates. 

Considering numbers ensuring validity on a date is not a straight forward as one might think. In this case it likely is best left up to user/dev in his/her own lib. Build a helper lib for a timestamp or something and this will become more obvious as to why I say this. Just my .02.

**Comment by taylorhakes** [comment] 2019-07-13 21:09
I am going to close this issue. If someone would like to submit a PR to add a strict version (which doesn't add a lot of code), I would be happy to add it

**Closed by taylorhakes** 2019-07-13 21:09 UTC
