### ISSUE TITLE
fecha.format doesn't print 4-digit year for YYYY

### ISSUE THREAD

**Issue by llech** [taylorhakes/fecha#42] opened 2018-02-21 09:52 UTC
I don't know if it's a bug or feature, but I was depending on fecha to set date-part to HTML5 date input, which expects date in format YYYY-MM-DD, where YYYY means 4-digit year.

However, fecha substitutes YYYY with Date.getFullYear() which is as long as it takes...

So the following code: 

```
var date = new Date('0999-10-09T22:00:00.000Z');
console.log(fecha.format(date, 'YYYY-MM-DD'));
```

Produces "999-10-10" instead of "0999-10-10". 

Is it intended behavior?

**Comment by taylorhakes** [comment] 2018-02-21 14:20
That is not intended behavior. Thanks for finding that bug @llech . I just pushed a fix in version `2.3.3`

**Closed by taylorhakes** 2018-02-21 14:20 UTC
